### ISSUE TITLE
GLSL 4.60: Typo - static use *of* gl_FragCoord

### ISSUE THREAD

**Issue by ThorStrikesAgain** [KhronosGroup/OpenGL-GLSL#5]
In section 4.4.1.3, we can read:

> gl_FragCoord is redeclared in any fragment shader in a program, it must be redeclared in all the fragment shaders in that program that have a static use [of] gl_FragCoord.

"of" is missing from the spec.

**Comment by johnkslang** [comment]
Applied to next pending revision.
