### ISSUE TITLE
 GLSL 4.60: Typo - Details for specific to

### ISSUE THREAD

**Issue by ThorStrikesAgain** [KhronosGroup/OpenGL-GLSL#6]
In section 4.4.6, we can read:

> Details **for** specific to image formats and atomic counter bindings are given in the subsections below.

The word "for" should probably be deleted.

**Comment by TobiasHector** [comment]
@johnkslang - looks like a straightforward bug to me. Not present in the ES spec, so assigning to you.

**Comment by johnkslang** [comment]
Done.
